---
- name: become_method sudo
  block:
    - name: install zabbix repository
      get_url:
        url: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian12_all.deb
        dest: /home/debian
    - name: dpkg
      apt:
        deb: zabbix-release_6.4-1+debian12_all.deb
    - name: update
      apt:
        update_cache: yes
  become: true
  become_method: sudo      
